#!/usr/bin/env node
import{createAccount,createClient}from'../frontend/node_modules/genlayer-js/dist/index.js';
import{studioDevnet}from'../frontend/node_modules/genlayer-js/dist/chains/index.js';
import{readFileSync}from'node:fs';
const MAIN=process.argv[2],EXECUTOR=process.argv[3],ADDRESS=/^0x[0-9a-fA-F]{40}$/;
if(!ADDRESS.test(MAIN||'')||!ADDRESS.test(EXECUTOR||''))throw Error('Usage: node scripts/run_live_e2e.mjs <main> <executor>');
const chain={...studioDevnet,id:61997,name:'GenLayer Studio Next',rpcUrls:{default:{http:['https://studio-next.genlayer.com/api']}}};
function hidden(prompt){return new Promise((resolve,reject)=>{process.stdout.write(prompt);process.stdin.setRawMode(true);process.stdin.resume();process.stdin.setEncoding('utf8');let value='';const done=()=>{process.stdin.off('data',onData);process.stdin.setRawMode(false);process.stdin.pause()};const onData=chunk=>{for(const ch of chunk){if(ch==='\u0003'){done();reject(Error('Interrupted'));return}if(ch==='\r'||ch==='\n'){done();process.stdout.write('\n');resolve(value.trim());return}if(ch==='\u007f'||ch==='\b')value=value.slice(0,-1);else value+=ch}};process.stdin.on('data',onData)})}
async function signer(label,key){const secret=key||await hidden(`${label} private key (hidden): `),account=createAccount(secret.startsWith('0x')?secret:`0x${secret}`);return{account,client:createClient({chain,account})}}
const localKey=readFileSync(new URL('./.test-wallet.env',import.meta.url),'utf8').trim().split('=',2)[1];
const publisher=await signer('publisher wallet A'),authority=await signer('authority wallet B'),requester=await signer('SDK requester wallet',localKey);
const actors=[publisher.account.address,authority.account.address,requester.account.address].map(x=>x.toLowerCase());if(new Set(actors).size!==3)throw Error('Three distinct actors required.');console.log(`actors=${actors.join(',')}`);
const read=(s,address,name,args=[])=>s.client.readContract({address,functionName:name,args,stateStatus:'finalized',jsonSafeReturn:true});
async function write(s,label,address,name,args,validators=300n){const fees=await s.client.estimateTransactionFees({leaderTimeunitsAllocation:300n,validatorTimeunitsAllocation:validators});const hash=await s.client.writeContract({account:s.account,address,functionName:name,args,value:0n,fees:{distribution:fees.distribution,feeValue:fees.feeValue}});console.log(`${label}.submitted=${hash}`);const receipt=await s.client.waitForTransactionReceipt({hash,waitUntil:'finalized',interval:3000,retries:600,fullTransaction:false});const tx=await s.client.getTransaction({hash}),consensus=String(tx.result_name||tx.result||'UNKNOWN');if(receipt?.txExecutionResultName&&receipt.txExecutionResultName!=='FINISHED_WITH_RETURN')throw Error(`${label} execution=${receipt.txExecutionResultName}`);if(!['AGREE','MAJORITY_AGREE'].includes(consensus))throw Error(`${label} consensus=${consensus}`);console.log(`${label}.finalized=${hash} consensus=${consensus}`);return hash}
const check=(ok,label,data)=>{if(!ok)throw Error(`${label}: ${JSON.stringify(data)}`);console.log(`${label}.readback=${JSON.stringify(data)}`)};
const policy='Commercial merchandise is allowed under 25000 units annual revenue. Gambling, tobacco, weapons, alcohol promotion, sublicensing, and AI training are prohibited. Direct convention apparel sales are permitted worldwide.';
const good='Print the licensed character on 500 convention T-shirts sold directly by the requester, with projected annual revenue of 12000 units. No sublicense or AI training is involved.';
const bad='Feature the licensed character as the mascot of a rewards campaign whose prizes and calls to action direct users to a real-money betting platform.';
const att='sha256:'+'a'.repeat(64),initial=await read(publisher,MAIN,'get_counts');check(Object.values(initial).every(x=>Number(x)===0),'clean V2 deployment',initial);
await write(publisher,'propose_policy',MAIN,'create_license',['Attested convention merchandise','0x'+'a'.repeat(40),'Collection-wide',policy,25000,2000000000,false,false,authority.account.address,att,'https://github.com/hathanh6819/LicenseLatch/blob/main/docs/TEST_RESOURCE_MANIFEST.md',EXECUTOR]);let lic=await read(publisher,MAIN,'get_license',[1]);check(lic.status==='AUTHORITY_PENDING'&&lic.authority===actors[1],'proposal pending authority',lic);
await write(requester,'unauthorized_attestation',MAIN,'confirm_license_authority',[1,1,att]);check((await read(requester,MAIN,'get_license',[1])).status==='AUTHORITY_PENDING','unauthorized attestation no mutation',await read(requester,MAIN,'get_license',[1]));
await write(authority,'authority_confirms',MAIN,'confirm_license_authority',[1,1,att]);lic=await read(authority,MAIN,'get_license',[1]);check(lic.status==='ACTIVE'&&Number(lic.epoch)===2,'authority activation',lic);
await write(requester,'submit_happy',MAIN,'submit_use_request',[1,lic.policy_digest,good,'Apparel','Worldwide',12000,false,false,'Synthetic direct-sales fixture documented in the repository.',requester.account.address,2]);let req=await read(requester,MAIN,'get_use_request',[1]);check(req.status==='SEMANTIC_PENDING','happy request pending',req);
await write(publisher,'assess_happy',MAIN,'assess_use_request',[1,req.request_digest],600n);req=await read(requester,MAIN,'get_use_request',[1]);let permission=await read(requester,MAIN,'get_permission',[1]);check(req.status==='APPROVED'&&permission.consumer===actors[2],'permission dispatched',{req,permission});
let authorization={};for(let i=0;i<20;i++){authorization=await read(requester,EXECUTOR,'get_authorization',[1]);if(authorization.status)break;await new Promise(r=>setTimeout(r,3000))}check(authorization.status==='ACTIVE'&&authorization.consumer===actors[2],'executor delivery',authorization);
await write(authority,'wrong_consumer_rejected',EXECUTOR,'consume_authorization',[1,permission.authorization_receipt]);check((await read(requester,EXECUTOR,'get_authorization',[1])).status==='ACTIVE','wrong consumer no mutation',await read(requester,EXECUTOR,'get_authorization',[1]));
await write(requester,'consumer_consumes',EXECUTOR,'consume_authorization',[1,permission.authorization_receipt]);authorization=await read(requester,EXECUTOR,'get_authorization',[1]);check(authorization.status==='CONSUMED','one-time consume',authorization);
await write(requester,'consume_replay_rejected',EXECUTOR,'consume_authorization',[1,permission.authorization_receipt]);check((await read(requester,EXECUTOR,'get_authorization',[1])).status==='CONSUMED','consume replay no mutation',await read(requester,EXECUTOR,'get_authorization',[1]));
await write(requester,'revenue_failure',MAIN,'submit_use_request',[1,lic.policy_digest,good,'Apparel','Worldwide',30000,false,false,'Synthetic revenue-boundary fixture in the repository.',requester.account.address,2]);let r2=await read(requester,MAIN,'get_use_request',[2]);check(r2.status==='REJECTED'&&r2.deterministic_reason==='REVENUE_CAP_EXCEEDED','deterministic rejection',r2);
await write(requester,'submit_conflict',MAIN,'submit_use_request',[1,lic.policy_digest,bad,'Betting promotion','Worldwide',8000,false,false,'Adversarial disguised-betting fixture documented in the repository.',requester.account.address,2]);let r3=await read(requester,MAIN,'get_use_request',[3]);await write(authority,'assess_conflict',MAIN,'assess_use_request',[3,r3.request_digest],600n);r3=await read(requester,MAIN,'get_use_request',[3]);check(['REJECTED','CONSENSUS_UNRESOLVED'].includes(r3.status),'semantic conflict fails closed',r3);
const counts=await read(publisher,MAIN,'get_counts');check(Number(counts.licenses)===1&&Number(counts.requests)===3&&Number(counts.permissions)===1,'final counts',counts);console.log('e2e.result=PASS');
