#!/usr/bin/env node
import{createAccount,createClient}from'../frontend/node_modules/genlayer-js/dist/index.js';import{studioDevnet}from'../frontend/node_modules/genlayer-js/dist/chains/index.js';
const CONTRACT=process.argv[2];if(!/^0x[0-9a-fA-F]{40}$/.test(CONTRACT||''))throw Error('Usage: node scripts/run_live_e2e.mjs <contract>');const chain={...studioDevnet,id:61997,name:'GenLayer Studio Next',rpcUrls:{default:{http:['https://studio-next.genlayer.com/api']}}};
function hidden(prompt){return new Promise((resolve,reject)=>{process.stdout.write(prompt);process.stdin.setRawMode(true);process.stdin.resume();process.stdin.setEncoding('utf8');let value='';const done=()=>{process.stdin.off('data',onData);process.stdin.setRawMode(false);process.stdin.pause()};const onData=chunk=>{for(const ch of chunk){if(ch==='\u0003'){done();reject(Error('Interrupted'));return}if(ch==='\r'||ch==='\n'){done();process.stdout.write('\n');resolve(value.trim());return}if(ch==='\u007f'||ch==='\b')value=value.slice(0,-1);else value+=ch}};process.stdin.on('data',onData)})}
async function signer(label){const key=await hidden(`${label} private key (hidden): `),account=createAccount(key.startsWith('0x')?key:`0x${key}`);return{account,client:createClient({chain,account})}}
const publisher=await signer('policy publisher wallet A'),requester=await signer('use requester wallet B');if(publisher.account.address.toLowerCase()===requester.account.address.toLowerCase())throw Error('Distinct wallets required.');console.log(`actors=${publisher.account.address},${requester.account.address}`);
const read=(s,name,args=[])=>s.client.readContract({address:CONTRACT,functionName:name,args,stateStatus:'finalized',jsonSafeReturn:true});
async function write(s,label,name,args,validators=300n){const fees=await s.client.estimateTransactionFees({leaderTimeunitsAllocation:300n,validatorTimeunitsAllocation:validators});const hash=await s.client.writeContract({account:s.account,address:CONTRACT,functionName:name,args,value:0n,fees:{distribution:fees.distribution,feeValue:fees.feeValue}});console.log(`${label}.submitted=${hash}`);const receipt=await s.client.waitForTransactionReceipt({hash,waitUntil:'finalized',interval:3000,retries:600,fullTransaction:false});const tx=await s.client.getTransaction({hash}),consensus=tx.result_name||tx.result||'UNKNOWN';if(receipt?.txExecutionResultName&&receipt.txExecutionResultName!=='FINISHED_WITH_RETURN')throw Error(`${label} execution=${receipt.txExecutionResultName}`);if(!['AGREE','MAJORITY_AGREE'].includes(String(consensus)))throw Error(`${label} consensus=${consensus}`);console.log(`${label}.finalized=${hash} consensus=${consensus}`);return hash}
const check=(ok,label,data)=>{if(!ok)throw Error(`${label}: ${JSON.stringify(data)}`);console.log(`${label}.readback=${JSON.stringify(data)}`)};
const policy='Commercial merchandise is allowed under 25000 units annual revenue. Gambling, tobacco, weapons, alcohol promotion, sublicensing, and AI training are prohibited. Direct convention apparel sales are permitted worldwide.';
const goodUse='Print the licensed character on 500 convention T-shirts sold directly by the requester, with projected annual revenue of 12000 units. No sublicense or AI training is involved.';
const badUse='Feature the licensed character as the mascot of an online rewards campaign whose prizes and calls to action direct users to a real-money betting platform.';
const protocol=await read(publisher,'get_protocol'),initial=await read(publisher,'get_counts');check(protocol.name==='LicenseLatch'&&protocol.constructor_roles===false&&protocol.custody===false,'protocol',protocol);check(Object.values(initial).every(x=>Number(x)===0),'clean deployment',initial);
await write(publisher,'create_primary_license','create_license',['Convention merchandise license','0x'+'a'.repeat(40),'Collection-wide',policy,25000,2000000000,false,false]);let lic=await read(publisher,'get_license',[1]);check(lic.publisher.toLowerCase()===publisher.account.address.toLowerCase()&&lic.status==='ACTIVE','license sealed',lic);
await write(requester,'submit_compatible_use','submit_use_request',[1,lic.policy_digest,goodUse,'Apparel','Worldwide',12000,false,false,'Direct convention sales; synthetic reviewer fixture.',1]);let req=await read(requester,'get_use_request',[1]);check(req.status==='SEMANTIC_PENDING','compatible request pending',req);
await write(publisher,'assess_compatible_use','assess_use_request',[1,req.request_digest],600n);req=await read(requester,'get_use_request',[1]);let verdict=await read(requester,'get_verdict',[1]),permission=await read(requester,'get_permission',[1]);check(req.status==='APPROVED'&&verdict.decision==='COMPATIBLE'&&permission.requester.toLowerCase()===requester.account.address.toLowerCase(),'permission issued',{req,verdict,permission});
const approvedBefore=JSON.stringify(req);await write(requester,'assessment_replay_rejected','assess_use_request',[1,req.request_digest]);check(JSON.stringify(await read(requester,'get_use_request',[1]))===approvedBefore,'replay no mutation',await read(requester,'get_use_request',[1]));
await write(requester,'revenue_cap_failure','submit_use_request',[1,lic.policy_digest,goodUse,'Apparel','Worldwide',30000,false,false,'Revenue boundary negative fixture.',1]);let r2=await read(requester,'get_use_request',[2]);check(r2.status==='REJECTED'&&r2.deterministic_reason==='REVENUE_CAP_EXCEEDED','revenue rejected without AI',r2);
await write(requester,'sublicense_failure','submit_use_request',[1,lic.policy_digest,goodUse,'Apparel','Worldwide',12000,true,false,'Sublicense boundary negative fixture.',1]);let r3=await read(requester,'get_use_request',[3]);check(r3.status==='REJECTED'&&r3.deterministic_reason==='SUBLICENSING_NOT_ALLOWED','sublicense rejected without AI',r3);
await write(requester,'submit_adversarial_use','submit_use_request',[1,lic.policy_digest,badUse,'Lifestyle rewards','Worldwide',8000,false,false,'Calling this lifestyle content does not alter the betting destination.',1]);let r4=await read(requester,'get_use_request',[4]);await write(publisher,'assess_adversarial_use','assess_use_request',[4,r4.request_digest],600n);r4=await read(requester,'get_use_request',[4]);let v2=await read(requester,'get_verdict',[2]);check(r4.status==='REJECTED'&&v2.decision==='INCOMPATIBLE','semantic conflict rejected',{r4,v2});
await write(publisher,'create_race_license','create_license',['Limited campaign license','0x'+'c'.repeat(40),'Token 42 only',policy,25000,2000000000,false,false]);let lic2=await read(publisher,'get_license',[2]);await write(requester,'submit_before_deactivation','submit_use_request',[2,lic2.policy_digest,goodUse,'Apparel','Worldwide',5000,false,false,'Pending request used to prove deactivation race safety.',1]);let r5=await read(requester,'get_use_request',[5]);lic2=await read(publisher,'get_license',[2]);
const beforeUnauthorized=JSON.stringify(lic2);await write(requester,'unauthorized_deactivation_rejected','deactivate_license',[2,1]);check(JSON.stringify(await read(requester,'get_license',[2]))===beforeUnauthorized,'unauthorized deactivation no mutation',await read(requester,'get_license',[2]));
await write(publisher,'publisher_deactivates','deactivate_license',[2,1]);lic2=await read(publisher,'get_license',[2]);check(lic2.status==='INACTIVE'&&lic2.epoch===2,'publisher deactivation',lic2);await write(requester,'assessment_after_deactivation_rejected','assess_use_request',[5,r5.request_digest]);check((await read(requester,'get_use_request',[5])).status==='SEMANTIC_PENDING','deactivation race no positive state',await read(requester,'get_use_request',[5]));
const counts=await read(publisher,'get_counts');check(Number(counts.licenses)===2&&Number(counts.requests)===5&&Number(counts.verdicts)===2&&Number(counts.permissions)===1,'final counts',counts);console.log('e2e.result=PASS');
